### ISSUE TITLE
Feature Request: Additional Positioning Option

### ISSUE THREAD

**Issue by n-jones0** [WesCook/HandyDandyNotebook#1]
Thanks for the great mod! Would it be possible to add an additional position option, near the top of the sidebar, below the bank? (the same placement that [Item Dashboard](https://mod.io/g/melvoridle/m/item-dashboard) uses)

![image](https://user-images.githubusercontent.com/21232805/231942352-bc23a5bd-adcf-44af-9b6a-2d348813402b.png)

**Comment by WesCook** [comment]
Thanks for your suggestion/request.  I've been considering moving the Notebook entry up for the sidebar positioning, rather than having it under the Modding submenu.  I was hesitant to push down the list of skills, but I think now it would have been the right choice from the beginning.

I am a little worried about breaking user's workflows or expectations at this point, but realistically, I think most people don't actually change from the default settings.  I'll likely implement that change in the near-future, and hope it doesn't beget any angry replies.

Thanks for the example of Item Dashboard.  I wasn't aware that other mods were adding to the sidebar, so that's a good point of reference.
