### ISSUE TITLE
lost all my notes

### ISSUE THREAD

**Issue by DayKk17** [WesCook/HandyDandyNotebook#2]
There's been a weird thing with Melvor, it sign me off randomly.. When I came to select another character, that's when I saw I was logged out. And then, I saw that my default mod setting was now empty with no mods. I quit the launcher, reopen it, logged back in, put my mods back on and then load back the game. But now all my notes are gone, I quite understand as Melvor "quit" using the mod.

So giving you the context, my question is: Is there any way that the mods save somewhere in the mods files what we are writing in there so it saved itself in a case like this? or just if you want to play vanilla and go back to your mods after, would all my notes be gone like this too?

**Comment by WesCook** [comment]
Unfortunately, the mod only saves notes to your Melvor character; nowhere else.  They will technically be stored temporarily in memory but once a page is refreshed that will be cleared, too.

As I understand it, Melvor will maintain mod data as long as a mod is installed.  If a mod is only disabled, that data is preserved.  But once it's fully removed, the data is wiped.

During a recent game update, a feature for mod profiles was introduced.  This allows you to assign a different mod loadout to each character/save slot.  I've not tested if this changes things, but my expectation is that characters where a mod is not assigned will simply count as disabling the mod, rather than uninstalling it.  Though I've not personally tested that.

I can only assume that when you loaded your character after being logged out, that the game was in a state where it considered the mod to be uninstalled, for whatever reason.  I'm afraid I don't know anything more beyond that.

I'm sorry to hear that you lost your notes.  It's the first report I've seen of that happening.  Unfortunately, I don't see any way that they could be recovered in this case.

For more information about how mods store data and what might have led to the loss, you may wish to check the mod discussions channel of the Discord server.  They'd likely be the best source to explain what happens when the game doesn't load in the correct state.
